modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "polylib"
version = "${version}"
displayName = "PolyLib"
authors = "CreeperHost"
description = '''
'''
#logoFile = ""

[[dependencies.polylib]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.polylib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.polylib]]
modId = "architectury"
mandatory = true
versionRange = "[3.6.15,)"
ordering = "AFTER"
side = "BOTH"
